### ISSUE TITLE
Performance benchmarks and unification suggestion

### ISSUE THREAD

**Issue by snk4tr** [francois-rozet/piqa#2]
Hey there.
I have a question regarding your claim on efficiency boost compared to [kornia](https://github.com/kornia/kornia), [piq](https://github.com/photosynthesis-team/piq) and [IQA-pytorch](https://github.com/dingkeyan93/IQA-optimization). Prevously, **4x speed up** was claimed. Currently, I see **up to 2x speed up** mentioned in the `README.md`. Could you provide any benchmarks that would support these statements? It would also be great to see if this performance boost holds in case of invalid or partically valid user data.
Another question is whether you considered to join the [piq](https://github.com/photosynthesis-team/piq) project. Your contribution to already well established library would be appreciated and could potentially bring more impact rather than development of a very similar product in parallel. If there are some reasons for not to join other than a wish to develop your own library, could you share them?

**Comment by francois-rozet** [comment]
Hello @snk4tr, the script I use for my benchmark is [`benchmark.py`](https://github.com/francois-rozet/piqa/blob/master/tests/benchmark.py).

Some of my implementations are 4x faster than those of [piq](https://github.com/photosynthesis-team/piq), at least on that benchmark. I changed it to 2x because it was only true for [piq](https://github.com/photosynthesis-team/piq).

Concerning invalid data, my implementations don't support invalid user inputs, but it is a **choice**. Asserting the input types (including memory device) is very resource consuming, especially for functions that are executed thousands of times. I believe that the potential users of `piqa` should be experienced enough to read the [documentation](https://francois-rozet.github.io/piqa/) in the case of errors.

This is one of the reason why I didn't want to join the [piq](https://github.com/photosynthesis-team/piq) project. Another one is that some features of `torch` are not well used in your code base. Especially, kernels are not buffered in oriented-object metrics (`SSIM`, `GMSD`, etc.), which means they are recomputed (and transferred to the device) each time the `forward` method is called. This is one of the reasons why my implementations are faster.

The best would probably have been to update your code base, but it would have taken much more time than starting from scratch, like I did. Moreover, I doubt you would have agreed to remove the input assertions. I also wanted to build my documentation with [pdoc](https://github.com/pdoc3/pdoc), which would not have been possible if I had joined [piq](https://github.com/photosynthesis-team/piq).

**Comment by snk4tr** [comment]
Thanks for your answer. The issue can be closed.

**Comment by francois-rozet** [comment]
Hello @snk4tr, I want to mention that I am not against contributing for `piq`. In fact, I am considering to export some of my implementations and tweaks to `piq`, so that everyone can take advantage of them 😃 However, it might require a few changes in `piq`. Would you like to talk about it (in private) ?

By the way, if you find something interesting in `piqa`, feel free to use it 😉
