### ISSUE TITLE
SSIM not working for negative numbers

### ISSUE THREAD

**Issue by ljeonjko** [francois-rozet/piqa#30]
Hi!

SSIM module isn't accepting negative numbers, as well as numbers greater than 1. This isn't an issue when working with photographic data, but when working with numerical data it's a hindrance.  E.g.`from skimage.metrics import structural_similarity` handles negative numbers well. Could you please implement this? Or is it enough for me to edit the lines in `ssim.py`?
Cheers!

**Comment by francois-rozet** [comment]
Hello,

The reason why the SSIM module does not accept negative numbers is because it does not work for negative numbers. If the inputs of the metric could be negative, both terms of SSIM (see [piqa.ssim.ssim](https://francois-rozet.github.io/piqa/piqa.ssim.html#piqa.ssim.ssim)) would range from `-1` to `1`. If both are equal to `-1`, it should mean that the input and the target are "perfectly dissimilar" but their product would be `1`, which indicates perfect similarity.

As a quick proof, if you compute the structural similarity of `x` and `-x` with `skimage` implementation, you would get something very close to `1`.

```python
>>> import numpy as np
>>> from skimage.metrics import structural_similarity as ssim
>>> x = np.random.rand(32, 32)
>>> ssim(x, -x)
0.9533197514910561
```

If you need to apply SSIM to numerical inputs with range `[-a, b]`, I would recommend to shift the range to `[0, a + b]`. If `a + b` is different than `1`, you can set the `value_range` parameter to `a + b`.

**Comment by ljeonjko** [comment]
Thanks for the advice about shifting the range and for pointing out the mistake in my metrics. You've saved me from a lot of bad results!
Cheers!

**Comment by ljeonjko** [comment]
Also, is there a way to dynamically set `value_range` as the maximum range won't be fixed for each batch of images? 
Cheers!

**Comment by francois-rozet** [comment]
I'm not sure what you mean by "not fixed for each batch of images". When i said if your numerical inputs range in `[a,b]`, I meant that a and b are the absolute minimum and maximum values of all the inputs, not in a batch. So they should not change "during training".

**Comment by ljeonjko** [comment]
Thank you very much for clarifying!
